Algoritmo "ex k 2 lista 1 bim"

Var

sexo:inteiro
nome:caractere

Inicio

escreval("digite seu nome(pressione enter)")
escreval("e digite o seu sexo(use 1 para feminino e 2 para masculino):")
				leia(nome)
				leia(sexo)


				se(sexo = 1)entao
					escreval("Ilma Srta.",nome)
             senao
						se(sexo = 2)entao
							escreval("Ilmo sr.", nome)
               fimse
            fimse

Fimalgoritmo